-- Generated by nwg-displays on 2026-09-23 at 22:41:07. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
