[dmenu]
#dmenu_command = rofi -dmenu -i -p "Сети:"
dmenu_command = rofi -dmenu -i -theme ~/.config/rofi/network.rasi
compact = true
# dmenu_command = wofi --dmenu --prompt "Сети:"

[dmenu_passphrase]
# Скрывать ввод пароля звездочками
obscure = True 

[editor]
terminal = kitty
gui_if_available = True


