-- HyprFlux — Auto-generated monitor config
-- Generated by modules/19-hardware-detect.sh at install time.
-- nwg-displays (>= 2.4) overwrites this file with its own Lua output.

-- Detected monitors (1 connected)
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1.0
})

-- Fallback: any monitor not matched above uses preferred mode
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1
})
